[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.13"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
# Base Sepolia endpoints
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${providerApiKey}"
 

[etherscan]
base_sepolia = { key = "${etherscanApiKey}" }